# Generated by Django 3.2.6 on 2021-09-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set_name', models.CharField(max_length=20, verbose_name='데이터 구축명')),
                ('start_cs', models.DateTimeField(verbose_name='크라우드소싱 시작일')),
                ('end_cs', models.DateTimeField(verbose_name='크라우드소싱 종료일')),
                ('reg_id', models.CharField(max_length=20, verbose_name='등록자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 일짜')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('data_base_path', models.CharField(max_length=200, verbose_name='데이터 저장 경로')),
            ],
        ),
        migrations.CreateModel(
            name='PayList',
            fields=[
                ('pay_num', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키(자동할당)')),
                ('task_num', models.CharField(max_length=30, verbose_name='상품 이름')),
                ('work_type', models.CharField(choices=[('A', '작업'), ('B', '1차 검수'), ('C', '2차 검수'), ('D', '3차 검수')], max_length=1, verbose_name='카테고리')),
                ('task_pay_count', models.IntegerField(default=0, verbose_name='작업 합산 금액')),
                ('inspect_1_pay_count', models.IntegerField(default=0, verbose_name='1차 검수 합산 금액')),
                ('inspect_2_pay_count', models.IntegerField(default=0, verbose_name='2차 검수 합산 금액')),
                ('inspect_3_pay_count', models.IntegerField(default=0, verbose_name='3차 검수 합산 금액')),
                ('total_pay_count', models.IntegerField(verbose_name='총 합산 금액')),
                ('reg_id', models.CharField(max_length=40, verbose_name='유저 이름')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='프로젝트 코드')),
                ('project_name', models.CharField(max_length=20, verbose_name='프로젝트 이름')),
                ('project_dc', models.CharField(max_length=200, verbose_name='프로젝트 설명')),
                ('bsn_nm', models.CharField(max_length=20, verbose_name='수행사업 이름')),
                ('hst_cmpy', models.CharField(max_length=20, verbose_name='주관기업 이름')),
                ('start_bn', models.DateTimeField(verbose_name='사업시작일')),
                ('end_bn', models.DateTimeField(verbose_name='사업종료일')),
                ('reg_id', models.CharField(max_length=20, verbose_name='등록자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 일자')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('project_status', models.CharField(choices=[('A', '프로젝트 대기'), ('B', '프로젝트 진행'), ('C', '프로젝트 완료'), ('D', '프로젝트 취소')], default='A', max_length=1, verbose_name='작업상태')),
            ],
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('task_num', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(작업 리스트)')),
                ('work_type', models.CharField(max_length=100, verbose_name='작업 종류')),
                ('video_path', models.CharField(max_length=100, verbose_name='비디오 저장 경로')),
                ('task_point', models.IntegerField(default=0, verbose_name='작업 단가')),
                ('task_status', models.CharField(choices=[('F', '작업 대기'), ('G', '작업 진행'), ('H', '작업 완료'), ('I', '작업 취소')], default='F', max_length=1, verbose_name='작업 상태')),
                ('task_user_id', models.CharField(max_length=40, null=True, verbose_name='작업자 ID')),
                ('task_start_date', models.DateTimeField(null=True, verbose_name='작업 시작 날짜')),
                ('task_end_date', models.DateTimeField(null=True, verbose_name='작업 종료 날짜')),
                ('inspect_point', models.IntegerField(default=0, verbose_name='1차 검수 단가')),
                ('inspect_status', models.CharField(choices=[('K', '1차 검수 대기'), ('L', '1차 검수 진행'), ('M', '1차 검수 완료'), ('N', '1차 검수 취소')], default='Z', max_length=1, verbose_name='1차 검수 상태')),
                ('inspect_user_id', models.CharField(max_length=40, null=True, verbose_name='검수자 ID')),
                ('inspect_start_date', models.DateTimeField(null=True, verbose_name='1차 검수 시작 날짜')),
                ('inspect_end_date', models.DateTimeField(null=True, verbose_name='1차 검수 종료 날짜')),
                ('inspect_point_2', models.IntegerField(default=0, verbose_name='2차 검수 단가')),
                ('inspect_status_2', models.CharField(choices=[('K', '1차 검수 대기'), ('L', '1차 검수 진행'), ('M', '1차 검수 완료'), ('N', '1차 검수 취소')], default='Z', max_length=1, verbose_name='2차 검수 상태')),
                ('inspect_user_id_2', models.CharField(max_length=40, null=True, verbose_name='검수자 ID')),
                ('inspect_start_date_2', models.DateTimeField(null=True, verbose_name='2차 검수 시작 날짜')),
                ('inspect_end_date_2', models.DateTimeField(null=True, verbose_name='2차 검수 종료 날짜')),
                ('inspect_point_3', models.IntegerField(default=0, verbose_name='3차 검수 단가')),
                ('inspect_status_3', models.CharField(choices=[('K', '1차 검수 대기'), ('L', '1차 검수 진행'), ('M', '1차 검수 완료'), ('N', '1차 검수 취소')], default='Z', max_length=1, verbose_name='3차 검수 상태')),
                ('inspect_user_id_3', models.CharField(max_length=40, null=True, verbose_name='검수자 ID')),
                ('inspect_start_date_3', models.DateTimeField(null=True, verbose_name='3차 검수 시작 날짜')),
                ('inspect_end_date_3', models.DateTimeField(null=True, verbose_name='3차 검수 종료 날짜')),
                ('data_set_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.datainfo', verbose_name='데이터 ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_num', models.CharField(max_length=40, verbose_name='작업 번호')),
                ('work_category', models.CharField(choices=[('AA', '작업 신청'), ('AB', '작업 완료'), ('AC', '작업 취소'), ('AD', '작업 반려'), ('AF', '1차 검수 신청'), ('AG', '1차 검수 완료'), ('AH', '1차 검수 취소'), ('AI', '1차 검수 반려'), ('AK', '2차 검수 신청'), ('AL', '2차 검수 완료'), ('AM', '2차 검수 취소'), ('AN', '2차 검수 반려')], max_length=10, verbose_name='카테고리')),
                ('reg_id', models.CharField(max_length=30, verbose_name='해당 작업자 ID')),
                ('reg_date', models.DateTimeField(verbose_name='등록 일자')),
                ('work_approved_date', models.DateTimeField(null=True, verbose_name='승인 일자')),
                ('worklist_task_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.worklist', verbose_name='외래키 : 작업 리스트 고유 번호')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(작업 내역)')),
                ('work_fold_path', models.CharField(max_length=100, verbose_name='대상 폴더 경로')),
                ('task_data', models.BinaryField(null=True, verbose_name='JSON 데이터(작업)')),
                ('task_image_num', models.IntegerField(verbose_name='작업한 이미지 번호')),
                ('tasker_id', models.CharField(max_length=20, verbose_name='작업자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('work_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키 : 자동 할당 번호 (WorkRecord)')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=200, verbose_name='아이디')),
                ('user_name', models.CharField(default='', max_length=100, verbose_name='이름')),
                ('phone_number', models.CharField(default='', max_length=30, verbose_name='전화번호')),
                ('email_address', models.CharField(default='', max_length=50, verbose_name='이메일 주소')),
                ('is_staff', models.BooleanField(default=False, verbose_name='접속 권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자 권한')),
                ('is_inspector', models.BooleanField(default=False, verbose_name='검수 권한')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='최종 로그인 날짜')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='가입 날짜')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspectHistory3',
            fields=[
                ('inspect_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(검수 내역)')),
                ('work_fold_path', models.CharField(max_length=100, verbose_name='대상 폴더 경로')),
                ('inspect_data', models.BinaryField(null=True, verbose_name='JSON 데이터(검수)')),
                ('inspect_image_num', models.IntegerField(verbose_name='작업한 이미지 번호')),
                ('inspector_id', models.CharField(max_length=20, verbose_name='검수자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('work_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키 : 자동 할당 번호 (WorkRecord)')),
            ],
        ),
        migrations.CreateModel(
            name='InspectHistory2',
            fields=[
                ('inspect_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(검수 내역)')),
                ('work_fold_path', models.CharField(max_length=100, verbose_name='대상 폴더 경로')),
                ('inspect_data', models.BinaryField(null=True, verbose_name='JSON 데이터(검수)')),
                ('inspect_image_num', models.IntegerField(verbose_name='작업한 이미지 번호')),
                ('inspector_id', models.CharField(max_length=20, verbose_name='검수자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('work_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키 : 자동 할당 번호 (WorkRecord)')),
            ],
        ),
        migrations.CreateModel(
            name='InspectHistory',
            fields=[
                ('inspect_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(검수 내역)')),
                ('work_fold_path', models.CharField(max_length=100, verbose_name='대상 폴더 경로')),
                ('inspect_data', models.BinaryField(null=True, verbose_name='JSON 데이터(검수)')),
                ('inspect_image_num', models.IntegerField(verbose_name='작업한 이미지 번호')),
                ('inspector_id', models.CharField(max_length=20, verbose_name='검수자 ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('work_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키 : 자동 할당 번호 (WorkRecord)')),
            ],
        ),
        migrations.CreateModel(
            name='DenyResonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_image_num', models.IntegerField(verbose_name='이미지 번호')),
                ('reason_detail_data', models.TextField(max_length=300, verbose_name='이미지 번호에 해당하는 반려 사유')),
                ('reg_id', models.CharField(max_length=30, verbose_name='등록자 ID')),
                ('reg_data', models.DateTimeField(auto_now=True, verbose_name='등록 날짜')),
                ('denyreason_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키(DenyReason)')),
            ],
        ),
        migrations.CreateModel(
            name='DenyReason',
            fields=[
                ('deny_primary_key', models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당(기본키')),
                ('task_num', models.CharField(max_length=40, verbose_name='상품 이름')),
                ('reason_data_field', models.TextField(max_length=300, null=True, verbose_name='해당 작업에 대한 전체 반려 사유')),
                ('task_type', models.CharField(choices=[('BA', '1차 검수 반려'), ('BB', '2차 검수 반려'), ('BC', '3차 검수 반려')], max_length=10, verbose_name='카테고리')),
                ('reg_id', models.CharField(max_length=30, verbose_name='등록자 ID')),
                ('reg_date', models.DateTimeField(auto_now=True, verbose_name='등록 날짜')),
                ('record_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.workrecord', verbose_name='외래키 : 자동 할당 번호 (WorkRecord)')),
            ],
        ),
        migrations.AddField(
            model_name='datainfo',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.projectinfo', verbose_name='프로젝트 코드'),
        ),
    ]
