# Generated by Django 3.2.7 on 2021-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklist',
            name='inspect_status_2',
            field=models.CharField(choices=[('P', '2차 검수 대기'), ('Q', '2차 검수 진행'), ('R', '2차 검수 완료'), ('S', '2차 검수 취소')], default='Z', max_length=1, verbose_name='2차 검수 상태'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='inspect_status_3',
            field=models.CharField(choices=[('U', '3차 검수 대기'), ('V', '3차 검수 진행'), ('W', '3차 검수 완료'), ('X', '3차 검수 취소')], default='Z', max_length=1, verbose_name='3차 검수 상태'),
        ),
    ]
