# Generated by Django 3.2.7 on 2021-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20210929_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='start_time',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task_image_num',
            field=models.IntegerField(default=0, verbose_name='작업한 이미지 번호'),
        ),
        migrations.AlterField(
            model_name='denyresondetail',
            name='task_image_num',
            field=models.IntegerField(default=0, verbose_name='이미지 번호'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(작업 내역)'),
        ),
    ]
