# Generated by Django 3.2.7 on 2021-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20210929_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='end_time',
            field=models.CharField(max_length=20, null=True, verbose_name='clip 종료시각'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='start_time',
            field=models.CharField(max_length=20, null=True, verbose_name='clip 시작시각'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='자동 할당 번호(clip ID)'),
        ),
    ]
