# Generated by Django 3.2.7 on 2021-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20210929_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task_data',
            field=models.TextField(null=True, verbose_name='JSON 데이터(작업)'),
        ),
    ]
