# Generated by Django 3.2.7 on 2021-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_alter_taskhistory_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='end_time',
            field=models.FloatField(max_length=20, null=True, verbose_name='clip 종료시각'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='start_time',
            field=models.FloatField(max_length=20, null=True, verbose_name='clip 시작시각'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_data',
            field=models.JSONField(null=True, verbose_name='JSON 데이터(작업)'),
        ),
    ]
