# Generated by Django 3.2.7 on 2021-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_auto_20211002_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task_data',
            field=models.JSONField(default='{}', verbose_name='JSON 데이터(작업)'),
        ),
    ]
