# Generated by Django 3.2.7 on 2021-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_alter_taskhistory_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='task_data',
            field=models.JSONField(default=dict, verbose_name='JSON 데이터(작업)'),
        ),
    ]
