# Generated by Django 3.2.7 on 2021-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_alter_taskhistory_task_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_id',
            field=models.CharField(default='gjac', max_length=20, verbose_name='소속 그룹'),
        ),
    ]
